# Generated by Django 5.1.4 on 2025-01-10 20:34

import app.models
import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='location_from',
        ),
        migrations.RemoveField(
            model_name='order',
            name='location_to',
        ),
        migrations.AlterField(
            model_name='car',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='', force_format=None, keep_meta=True, quality=-1, scale=None, size=[1440, 810], upload_to=app.models.get_car_image_path),
        ),
    ]
